
-- Authors: c23_12345, DevelopBanana, mainna1 
--What is our game?:
--[[Core Gameplay Loop

Furniture (randomized in type, size, and location) falls from the sky.

Players must race to sit on a piece of furniture.

One player is left standing and they get eliminated.

The next round begins with fewer players.

Repeat until 1 winner remains.

Objects:
-Chair Model
-Sofa Model
-Bed Model
-Player
Furniture (chairs, sofas, beds)
Players





]]

-- Version 1.0.0

